"""Add account_categories, account_category_resource_types, and user_accounts.account_category_id.

Introduces a client-category dimension used to restrict which resource types an
account may mint (multi-tenant data hiding, step 1). Orthogonal to account_types.

Revision ID: c8f1a3d4e5b6
Revises: a7c9e2f4b6d8
Create Date: 2026-07-29
"""

from alembic import op
import sqlalchemy as sa


revision = 'c8f1a3d4e5b6'
down_revision = 'a7c9e2f4b6d8'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'account_categories',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('category_name', sa.String(length=50), nullable=False),
        sa.Column('is_restricted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('category_name', name='uq_account_categories_category_name'),
    )

    op.create_table(
        'account_category_resource_types',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('account_category_id', sa.Integer(), nullable=False),
        sa.Column('resource_type_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['account_category_id'], ['account_categories.id'],
            name='fk_acct_category_resource_type_category', ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['resource_type_id'], ['resource_types.id'],
            name='fk_acct_category_resource_type_resource', ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('account_category_id', 'resource_type_id', name='uq_acct_category_resource_type'),
    )
    # Names match SQLAlchemy's index=True autogenerated names (ix_<table>_<col>) so
    # future Alembic autogeneration does not see spurious drift.
    op.create_index('ix_account_category_resource_types_account_category_id', 'account_category_resource_types', ['account_category_id'])
    op.create_index('ix_account_category_resource_types_resource_type_id', 'account_category_resource_types', ['resource_type_id'])

    op.add_column('user_accounts', sa.Column('account_category_id', sa.Integer(), nullable=True))
    op.create_index('ix_user_accounts_account_category_id', 'user_accounts', ['account_category_id'])
    op.create_foreign_key(
        'fk_user_accounts_account_category', 'user_accounts', 'account_categories',
        ['account_category_id'], ['id'],
    )


def downgrade():
    op.drop_constraint('fk_user_accounts_account_category', 'user_accounts', type_='foreignkey')
    op.drop_index('ix_user_accounts_account_category_id', table_name='user_accounts')
    op.drop_column('user_accounts', 'account_category_id')

    op.drop_index('ix_account_category_resource_types_resource_type_id', table_name='account_category_resource_types')
    op.drop_index('ix_account_category_resource_types_account_category_id', table_name='account_category_resource_types')
    op.drop_table('account_category_resource_types')

    op.drop_table('account_categories')
